name: modern_form_menu
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/apps-auth/modern_form_menu
homepage: https://github.com/apps-auth/modern_form_menu

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  get: ">=3.24.0 <4.0.0"
  flutter_screenutil: ">=3.1.1 <3.1.2"
  modern_form: ">=0.0.2-prerelease <1.0.2-prerelease"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
