name: modern_form_menu
description: A new Flutter package project.
version: 1.0.0
repository: https://github.com/apps-auth/modern_form_menu
homepage: https://github.com/apps-auth/modern_form_menu

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  get: '>=4.3.8 <5.0.0'
  flutter_screenutil: '>=5.0.0+2 <6.0.0'
  modern_form: ">=1.0.0 <2.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
